#!/usr/bin/env node
/**
 * embed-dist.mjs
 *
 * Reads all non-source-map files from the Vite build output (dist/) and
 * generates dist-assets.js, which inlines their content as base64 strings
 * inside a JavaScript Map.
 *
 * cli.js imports dist-assets.js statically so that Bun's --compile bundler
 * picks up the module and embeds every asset into the compiled binary.
 * The server then decodes the base64 values at startup and serves them
 * directly from memory -- no filesystem access is required at runtime.
 *
 * Usage:
 *   node scripts/embed-dist.mjs
 *
 * Environment variables (used by tests to redirect paths):
 *   DIST_DIR    - path to the dist directory (default: ../dist relative to this script)
 *   OUTPUT_PATH - path to write dist-assets.js  (default: ../dist-assets.js)
 */

import { readFileSync, readdirSync, statSync, writeFileSync, existsSync } from 'node:fs';
import { join, extname, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const distDir = process.env.DIST_DIR ?? join(__dirname, '..', 'dist');
const outputPath = process.env.OUTPUT_PATH ?? join(__dirname, '..', 'dist-assets.js');

const MIME_TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.mjs': 'application/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.png': 'image/png',
  '.woff2': 'font/woff2',
};

if (!existsSync(distDir)) {
  console.error(`Error: dist directory not found at ${distDir}`);
  console.error('Run "npm run build" first.');
  process.exit(1);
}

/**
 * Recursively collect all embeddable files under rootDir.
 * Source maps (.map) are excluded -- they are large and not needed at runtime.
 *
 * @param {string} dir       Current directory being scanned.
 * @param {string} rootDir   Root of the dist tree (used to compute URL paths).
 * @returns {{ urlPath: string, mimeType: string, content: string }[]}
 */
function collectFiles(dir, rootDir = dir) {
  const entries = [];
  for (const name of readdirSync(dir)) {
    const fullPath = join(dir, name);
    if (statSync(fullPath).isDirectory()) {
      entries.push(...collectFiles(fullPath, rootDir));
    } else {
      // Exclude source maps -- large and not needed in a production binary.
      if (name.endsWith('.map')) continue;
      const urlPath = '/' + relative(rootDir, fullPath).replace(/\\/g, '/');
      const ext = extname(name).toLowerCase();
      const mimeType = MIME_TYPES[ext] ?? 'application/octet-stream';
      const content = readFileSync(fullPath).toString('base64');
      entries.push({ urlPath, mimeType, content });
    }
  }
  return entries;
}

const files = collectFiles(distDir);

const lines = [
  '// Auto-generated by scripts/embed-dist.mjs -- do NOT edit by hand.',
  '// Run `npm run embed` (after `npm run build`) to regenerate.',
  '// When this map is empty the CLI server falls back to filesystem serving (dev mode).',
  '// The populated version of this file should NOT be committed to source control.',
  '',
  '/** @type {Map<string, { content: string, mimeType: string }>} */',
  'export const distAssets = new Map([',
  ...files.map(
    ({ urlPath, content, mimeType }) =>
      `  [${JSON.stringify(urlPath)}, { content: ${JSON.stringify(content)}, mimeType: ${JSON.stringify(mimeType)} }],`,
  ),
  ']);',
];

writeFileSync(outputPath, lines.join('\n') + '\n', 'utf8');

console.log(`Embedded ${files.length} dist assets into dist-assets.js`);
for (const { urlPath } of files) {
  console.log(`  ${urlPath}`);
}
