package net.agentensemble.delegation;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.util.Map;
import org.junit.jupiter.api.Test;

class DelegationRequestTest {

    // ========================
    // Builder basics
    // ========================

    @Test
    void testBuild_withRequiredFields_succeeds() {
        DelegationRequest request = DelegationRequest.builder()
                .agentRole("Analyst")
                .taskDescription("Analyse Q3 data")
                .build();

        assertThat(request.getAgentRole()).isEqualTo("Analyst");
        assertThat(request.getTaskDescription()).isEqualTo("Analyse Q3 data");
    }

    @Test
    void testBuild_missingAgentRole_throwsNullPointerException() {
        assertThatThrownBy(() -> DelegationRequest.builder()
                        .taskDescription("Some description")
                        .build())
                .isInstanceOf(NullPointerException.class);
    }

    @Test
    void testBuild_missingTaskDescription_throwsNullPointerException() {
        assertThatThrownBy(
                        () -> DelegationRequest.builder().agentRole("Analyst").build())
                .isInstanceOf(NullPointerException.class);
    }

    // ========================
    // Auto-UUID taskId
    // ========================

    @Test
    void testTaskId_isAutoGeneratedWhenNotSet() {
        DelegationRequest request = DelegationRequest.builder()
                .agentRole("Analyst")
                .taskDescription("Task")
                .build();

        assertThat(request.getTaskId()).isNotNull().isNotBlank();
    }

    @Test
    void testTaskId_isUniquePerBuild() {
        DelegationRequest r1 = DelegationRequest.builder()
                .agentRole("Analyst")
                .taskDescription("Task")
                .build();
        DelegationRequest r2 = DelegationRequest.builder()
                .agentRole("Analyst")
                .taskDescription("Task")
                .build();

        assertThat(r1.getTaskId()).isNotEqualTo(r2.getTaskId());
    }

    @Test
    void testTaskId_canBeSetExplicitly() {
        DelegationRequest request = DelegationRequest.builder()
                .taskId("fixed-id-123")
                .agentRole("Analyst")
                .taskDescription("Task")
                .build();

        assertThat(request.getTaskId()).isEqualTo("fixed-id-123");
    }

    // ========================
    // Default field values
    // ========================

    @Test
    void testPriority_defaultIsNormal() {
        DelegationRequest request = DelegationRequest.builder()
                .agentRole("Analyst")
                .taskDescription("Task")
                .build();

        assertThat(request.getPriority()).isEqualTo(DelegationPriority.NORMAL);
    }

    @Test
    void testScope_defaultIsEmptyMap() {
        DelegationRequest request = DelegationRequest.builder()
                .agentRole("Analyst")
                .taskDescription("Task")
                .build();

        assertThat(request.getScope()).isEmpty();
    }

    @Test
    void testMetadata_defaultIsEmptyMap() {
        DelegationRequest request = DelegationRequest.builder()
                .agentRole("Analyst")
                .taskDescription("Task")
                .build();

        assertThat(request.getMetadata()).isEmpty();
    }

    @Test
    void testMaxOutputRetries_defaultIsZero() {
        DelegationRequest request = DelegationRequest.builder()
                .agentRole("Analyst")
                .taskDescription("Task")
                .build();

        assertThat(request.getMaxOutputRetries()).isZero();
    }

    @Test
    void testExpectedOutputSchema_defaultIsNull() {
        DelegationRequest request = DelegationRequest.builder()
                .agentRole("Analyst")
                .taskDescription("Task")
                .build();

        assertThat(request.getExpectedOutputSchema()).isNull();
    }

    // ========================
    // Optional field overrides
    // ========================

    @Test
    void testPriority_canBeSetToHigh() {
        DelegationRequest request = DelegationRequest.builder()
                .agentRole("Analyst")
                .taskDescription("Task")
                .priority(DelegationPriority.HIGH)
                .build();

        assertThat(request.getPriority()).isEqualTo(DelegationPriority.HIGH);
    }

    @Test
    void testScope_canBePopulated() {
        DelegationRequest request = DelegationRequest.builder()
                .agentRole("Analyst")
                .taskDescription("Task")
                .scope(Map.of("project", "Alpha"))
                .build();

        assertThat(request.getScope()).containsEntry("project", "Alpha");
    }

    @Test
    void testMetadata_canBePopulated() {
        DelegationRequest request = DelegationRequest.builder()
                .agentRole("Analyst")
                .taskDescription("Task")
                .metadata(Map.of("source", "pipeline-A"))
                .build();

        assertThat(request.getMetadata()).containsEntry("source", "pipeline-A");
    }

    @Test
    void testExpectedOutputSchema_canBeSet() {
        DelegationRequest request = DelegationRequest.builder()
                .agentRole("Analyst")
                .taskDescription("Task")
                .expectedOutputSchema("JSON schema: { ... }")
                .build();

        assertThat(request.getExpectedOutputSchema()).isEqualTo("JSON schema: { ... }");
    }

    @Test
    void testMaxOutputRetries_canBeSet() {
        DelegationRequest request = DelegationRequest.builder()
                .agentRole("Analyst")
                .taskDescription("Task")
                .maxOutputRetries(3)
                .build();

        assertThat(request.getMaxOutputRetries()).isEqualTo(3);
    }

    // ========================
    // toBuilder
    // ========================

    @Test
    void testToBuilder_preservesTaskId() {
        DelegationRequest original = DelegationRequest.builder()
                .agentRole("Analyst")
                .taskDescription("Task")
                .build();

        DelegationRequest copy = original.toBuilder().agentRole("Writer").build();

        assertThat(copy.getTaskId()).isEqualTo(original.getTaskId());
        assertThat(copy.getAgentRole()).isEqualTo("Writer");
    }
}
