// Auto-generated by scripts/embed-dist.mjs -- do NOT edit by hand.
// Run `npm run embed` (after `npm run build`) to regenerate.
// When this map is empty the CLI server falls back to filesystem serving (dev mode).
// The populated version of this file should NOT be committed to source control.

/** @type {Map<string, { content: string, mimeType: string }>} */
export const distAssets = new Map();
