package net.agentensemble.devtools.dag;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.PropertyAccessor;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.List;
import lombok.Builder;
import lombok.NonNull;
import lombok.Singular;
import lombok.Value;

/**
 * Pre-execution snapshot of an ensemble's task dependency graph.
 *
 * <p>Generated by {@link DagExporter} from an {@link net.agentensemble.Ensemble} configuration
 * before the ensemble is run. Contains the full dependency structure, agent metadata, and
 * computed layout hints (parallel groups, critical path) needed to render an execution graph.
 *
 * <p>The {@code "type": "dag"} field distinguishes this format from an
 * {@link net.agentensemble.trace.ExecutionTrace} (post-execution trace) when both types
 * are consumed by the same visualization tool.
 *
 * <h2>JSON export</h2>
 *
 * <pre>
 * DagModel dag = EnsembleDevTools.buildDag(ensemble);
 *
 * // Get as string
 * String json = dag.toJson();
 *
 * // Write to file
 * dag.toJson(Path.of("./traces/my-run.dag.json"));
 * </pre>
 *
 * <h2>Schema versioning</h2>
 *
 * <p>Consumers should check the {@code schemaVersion} field before parsing to ensure
 * compatibility with their supported schema version.
 */
@Value
@Builder
public class DagModel {

    /**
     * Current schema version for the DAG model format.
     *
     * <p>History:
     * <ul>
     *   <li>1.0 -- initial release</li>
     *   <li>1.1 -- added {@code mapReduceMode} on {@link DagModel} and
     *       {@code nodeType}/{@code mapReduceLevel} on {@link DagTaskNode}</li>
     *   <li>1.2 -- added {@code "loop"} {@code nodeType} for
     *       {@link net.agentensemble.workflow.loop.Loop} super-nodes with
     *       {@code loopMaxIterations} and {@code loopBody} child task list</li>
     *   <li>1.3 -- added {@code mode = "graph"} for
     *       {@link net.agentensemble.workflow.graph.Graph} state-machine ensembles, plus
     *       {@code "graph-state"} {@code nodeType} on {@link DagTaskNode} and a top-level
     *       {@code graphEdges} list with conditional / fired metadata</li>
     * </ul>
     */
    public static final String CURRENT_SCHEMA_VERSION = "1.3";

    private static final ObjectMapper MAPPER = buildObjectMapper();

    /**
     * Schema version identifier.
     * Defaults to {@link #CURRENT_SCHEMA_VERSION}.
     */
    @Builder.Default
    String schemaVersion = CURRENT_SCHEMA_VERSION;

    /**
     * File type discriminator.
     * Always {@code "dag"} for this format, enabling consumers to distinguish
     * DAG files from trace files without inspecting other fields.
     */
    @Builder.Default
    String type = "dag";

    /**
     * The workflow strategy configured on the ensemble.
     * One of {@code "SEQUENTIAL"}, {@code "PARALLEL"}, or {@code "HIERARCHICAL"}.
     */
    @NonNull
    String workflow;

    /** Wall-clock instant when this DAG model was generated. */
    @NonNull
    Instant generatedAt;

    /**
     * Snapshots of all agents registered with the ensemble, in registration order.
     */
    @Singular
    List<DagAgentNode> agents;

    /**
     * All tasks in the ensemble, in the order they were registered.
     * Each task node includes its dependencies, parallel group, and critical path membership.
     */
    @Singular
    List<DagTaskNode> tasks;

    /**
     * Topological levels of the dependency graph, from level 0 (roots) to the deepest level.
     *
     * <p>Each inner list contains the task IDs that belong to that topological level.
     * Tasks within the same level have no dependencies on each other and can potentially
     * run in parallel. Level 0 contains all root tasks (those with no in-graph dependencies).
     *
     * <p>Example: {@code [["0", "2"], ["1"], ["3"]]} means tasks 0 and 2 can run first in
     * parallel, then task 1 (which depends on 0 or 2), then task 3.
     */
    List<List<String>> parallelGroups;

    /**
     * Ordered list of task IDs forming the critical path through the DAG.
     *
     * <p>The critical path is the longest sequential chain of dependent tasks from any
     * root to any leaf. Completing all tasks on the critical path as quickly as possible
     * minimizes total ensemble execution time.
     */
    List<String> criticalPath;

    /**
     * Map-reduce reduction strategy, when this DAG was generated from a
     * {@link net.agentensemble.mapreduce.MapReduceEnsemble}.
     *
     * <p>One of {@code "STATIC"} or {@code "ADAPTIVE"}.
     * {@code null} for standard (non-MapReduce) ensembles.
     */
    String mapReduceMode;

    /**
     * Top-level shape discriminator. {@code null} for legacy DAG ensembles (tasks /
     * loops / phases); {@code "graph"} for {@link net.agentensemble.workflow.graph.Graph}
     * state-machine ensembles. Schema 1.3+. When set, {@link #graphEdges},
     * {@link #graphStartStateId}, and friends are populated and the {@code tasks} list
     * carries state nodes ({@code nodeType = "graph-state"}).
     */
    String mode;

    /**
     * Edge list for graph ensembles. Each entry connects two state nodes (or a state to
     * the implicit {@code "__END__"} sentinel) with optional conditional metadata.
     * {@code null} for non-graph ensembles.
     */
    List<DagGraphEdge> graphEdges;

    /** Start-state id for graph ensembles. {@code null} for non-graph ensembles. */
    String graphStartStateId;

    /**
     * Termination reason for graph ensembles, populated post-execution by
     * {@code DagExporter.build(graph, graphTrace)}. {@code "terminal"} or {@code "maxSteps"}.
     * {@code null} pre-execution or for non-graph ensembles.
     */
    String graphTerminationReason;

    /**
     * Number of steps actually run, populated post-execution. {@code null} pre-execution
     * or for non-graph ensembles.
     */
    Integer graphStepsRun;

    // ========================
    // JSON export methods
    // ========================

    /**
     * Serialize this DAG model to a pretty-printed JSON string.
     *
     * @return the JSON representation
     * @throws UncheckedIOException if serialization fails
     */
    public String toJson() {
        try {
            return MAPPER.writerWithDefaultPrettyPrinter().writeValueAsString(this);
        } catch (IOException e) {
            throw new UncheckedIOException("Failed to serialize DagModel to JSON", e);
        }
    }

    /**
     * Write this DAG model as pretty-printed JSON to the specified file path.
     *
     * <p>Parent directories are created if they do not already exist.
     *
     * @param outputPath the path to write the JSON file; must not be {@code null}
     * @throws UncheckedIOException if the file cannot be written or serialization fails
     */
    public void toJson(Path outputPath) {
        try {
            Path parent = outputPath.getParent();
            if (parent != null) {
                Files.createDirectories(parent);
            }
            MAPPER.writerWithDefaultPrettyPrinter().writeValue(outputPath.toFile(), this);
        } catch (IOException e) {
            throw new UncheckedIOException("Failed to write DagModel to " + outputPath, e);
        }
    }

    private static ObjectMapper buildObjectMapper() {
        ObjectMapper mapper = new ObjectMapper();
        mapper.registerModule(new JavaTimeModule());
        mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
        mapper.disable(SerializationFeature.WRITE_DURATIONS_AS_TIMESTAMPS);
        mapper.setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY);
        return mapper;
    }
}
